# Generated by Django 5.1.2 on 2024-10-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytable',
            name='category_image',
        ),
    ]
