# Generated by Django 5.1.2 on 2024-10-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0003_author_language_booktable_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
