# Generated by Django 5.1.2 on 2024-10-31 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0004_alter_booktable_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booktable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside_app.booktable'),
        ),
    ]
